import View
problem1 = View.View()
problem1.select_all()
problem1.render(1)
print('---------------------------------')
problem2 = View.View()
problem2.select_top()
problem2.render(2)
print('----------------------------------')
problem3 = View.View()
problem3.select_top_student()
problem3.render(3)
print('----------------------------------')
problem4 = View.View()
problem4.create_table()
problem4.render(4)
print('-----------------------------------')
problem5 = View.View()
problem5.find_status()
problem5.render(5)
